from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import re
import os


def markdown_to_pdf(markdown_text: str, output_path: str, topic: str):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2.5 * cm,
        leftMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
        leading=28,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#666666"),
        spaceAfter=20,
        alignment=TA_LEFT,
    )
    h2_style = ParagraphStyle(
        "H2",
        parent=styles["Heading2"],
        fontSize=15,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=18,
        spaceAfter=6,
        borderPad=4,
    )
    h3_style = ParagraphStyle(
        "H3",
        parent=styles["Heading3"],
        fontSize=12,
        textColor=colors.HexColor("#2d6a4f"),
        spaceBefore=12,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=16,
        textColor=colors.HexColor("#2c2c2c"),
        spaceAfter=8,
    )
    bullet_style = ParagraphStyle(
        "Bullet",
        parent=styles["Normal"],
        fontSize=10.5,
        leading=16,
        leftIndent=16,
        firstLineIndent=0,
        textColor=colors.HexColor("#2c2c2c"),
        spaceAfter=4,
        bulletIndent=6,
    )
    caption_style = ParagraphStyle(
        "Caption",
        parent=styles["Normal"],
        fontSize=8.5,
        textColor=colors.HexColor("#888888"),
        spaceAfter=20,
    )

    story = []

    # Header block
    story.append(Paragraph(topic, title_style))
    story.append(Paragraph("Research Report — Generated by AI Research Agent (CrewAI)", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 14))

    lines = markdown_text.split("\n")

    for line in lines:
        line = line.strip()

        if not line:
            story.append(Spacer(1, 4))
            continue

        # Skip the first H1 (already rendered as title above)
        if line.startswith("# "):
            continue

        elif line.startswith("## "):
            text = line[3:].strip()
            story.append(Spacer(1, 6))
            story.append(Paragraph(text, h2_style))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd")))

        elif line.startswith("### "):
            text = line[4:].strip()
            story.append(Paragraph(text, h3_style))

        elif line.startswith("- ") or line.startswith("* "):
            text = line[2:].strip()
            text = _clean_inline(text)
            story.append(Paragraph(f"&#8226; &nbsp; {text}", bullet_style))

        elif re.match(r"^\d+\.\s", line):
            text = re.sub(r"^\d+\.\s", "", line).strip()
            text = _clean_inline(text)
            story.append(Paragraph(f"&#8226; &nbsp; {text}", bullet_style))

        elif line.startswith("**") and line.endswith("**") and len(line) > 4:
            text = line[2:-2]
            story.append(Paragraph(f"<b>{text}</b>", body_style))

        elif line.startswith("---") or line.startswith("___"):
            story.append(Spacer(1, 4))
            story.append(HRFlowable(width="100%", thickness=0.4, color=colors.HexColor("#eeeeee")))
            story.append(Spacer(1, 4))

        else:
            text = _clean_inline(line)
            story.append(Paragraph(text, body_style))

    # Footer note
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd")))
    story.append(Paragraph(
        "Generated by AI Research Agent · Built with CrewAI · github.com/muhammadabdullah12345",
        caption_style
    ))

    doc.build(story)
    return output_path


def _clean_inline(text: str) -> str:
    """Convert inline markdown to ReportLab XML."""
    # Bold+italic
    text = re.sub(r"\*\*\*(.*?)\*\*\*", r"<b><i>\1</i></b>", text)
    # Bold
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    # Italic
    text = re.sub(r"\*(.*?)\*", r"<i>\1</i>", text)
    # Inline code
    text = re.sub(r"`(.*?)`", r"<font name='Courier'>\1</font>", text)
    # Strip markdown links but keep text: [text](url) -> text
    text = re.sub(r"\[(.*?)\]\(.*?\)", r"\1", text)
    # Escape & and < that aren't our XML tags
    # (Do this carefully — only bare & not already &amp;)
    text = re.sub(r"&(?!amp;|lt;|gt;|#\d+;|[a-z]+;)", "&amp;", text)
    return text